name: Deploy to staging

on:
  push:
    branches: [ develop ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1.13.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Next.js
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          tags: ghcr.io/mimic-finance/mimic-farm-v2:develop
          secrets: |
            "dotenv=${{ secrets.DOTENV }}"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u USERNAME --password-stdin
            docker stop mimic-farm-v2-develop || true && docker rm mimic-farm-v2-develop || true
            docker rmi ghcr.io/mimic-finance/mimic-farm-v2:develop
            docker pull ghcr.io/mimic-finance/mimic-farm-v2:develop
            docker run -p 3100:3000 -d --name mimic-farm-v2-develop ghcr.io/mimic-finance/mimic-farm-v2:develop
